### ISSUE TITLE
[Feature]: Set arbitrary min/max card height

### ISSUE THREAD

**Issue by bjorndotwork** [mgmeyers/obsidian-kanban#332]
### Goal or desired outcome of this feature

Ability to set minimum and maximum card height by lines and/or by pixels would be fantastic for making them feel… more like actual cards (and more like Trello).

### Describe the feature

See goal.

**Comment by ronan-smith** [comment]
I use task lists inside cards and this can make cards become quite unwieldily. Wonder if there's a CSS snippet we can use in Obsidian as a workaround?

I'm not sure which CSS selector targets the cards but I'd imaging setting a pixel `height` value and setting `overflow: scroll` would be a good start?

**Comment by ronan-smith** [comment]
To @bjornfiles and for anyone else interested in a workaround, I've got the following working successfully:

```css
.kanban-plugin__item {
  max-height: 200px;
  overflow-y: scroll;
}
```

**Add the CSS to a blank CSS file, mine is called `kanban-height.css`, and then add this to Obsidian's snippet folder - enable it under the Appearance menu at the bottom.**

This currently also effects the cards while they are being edited, which might be unwanted, perhaps there's another CSS class that can be added to the selector to show the cards normally when they are being modified. Can @mgmeyers provide the correct selector?

**Comment by v3rso** [comment]
Going off of @ronan-smith's workaround, the following expands the card while it's being edited.

```css
.kanban-plugin__item {
    max-height: 200px;
    overflow-y: scroll;

    &:has(.markdown-source-view) {
        max-height: none;
        overflow-y: visible;
    }
}
```
