### ISSUE TITLE
[Feature]: Limit card height and add scrolling inside the card

### ISSUE THREAD

**Issue by Capaldi12** [mgmeyers/obsidian-kanban#469]
### Goal or desired outcome of this feature

When I add too much text to the card or include too big note/section, it stretches out and takes all screen height, pushing other cards out of the screen. It would be nice to have card just hide extra content under scrollbar so it does not take up all screen.

### Describe the feature

My idea is to set limit to card height and hide overflow, and add scrollbar to view entire card contents. When editing card, it should open in full. Maybe also add some sort of a focus, so when card is in foucs, it's shown in full, and limited to set height otherwise.

### Can you think of any alternatives or work-arounds?

It is possible to put all of this text to the note and just reference the not inside the card, but it's not ideal in some situations.

**Comment by huyz** [comment]
Possible alternatives:
- Fold all card content after the first line, leaving a triangle that can be clicked to expand the content.
- Limit height (showing as much as the card content as will fit) and, if there's overflow, then display a "more..." link that when clicked makes the card take full height
- hover to see popup with the rest of the card content

**Comment by Rhydderch** [comment]
I did this with a css snippet.

I guess this is the result you would like to get?
<img width="310" alt="image" src="https://user-images.githubusercontent.com/3197629/194562286-00062871-24f0-49ae-82c8-7e1ba21f46a7.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/3197629/194562547-32d5fbfa-d2e1-48d5-a853-a86aea6b106d.png">

```css
.kanban-plugin__lane-items>div {
    padding-top: 3px;
    padding-bottom: 3px;
    padding-right:3px;
    padding-left:3px;
}
div.markdown-preview-view.kanban-plugin__markdown-preview-view.kanban-plugin__item-markdown {
    max-height: 350px;
    overflow: scroll;
    padding-bottom: 10px;
    margin-bottom: -10px;
}

div.markdown-preview-view.kanban-plugin__markdown-preview-view.kanban-plugin__item-markdown::-webkit-scrollbar {
    
}

.kanban-plugin__embed-link{
    margin:5px;
    z-index: 999;
    position:relative;
}


.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h1,
.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h2,
.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h3,
.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h4,
.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h5,
.markdown-preview-view .kanban-plugin__markdown-preview-view  > div:nth-child(2) > h6 { 
  /*display: none*/
}

.markdown-preview-view .markdown-embed-title {
    display: none;
  }

  .markdown-preview-view .markdown-embed h5 {
	display: none;
}
```
