### ISSUE TITLE
[Feature]: option to turn off card counter in list title

### ISSUE THREAD

**Issue by firinael** [mgmeyers/obsidian-kanban#523]
### Goal or desired outcome of this feature

I have no use for the counter and it's taking up space in the header. Would like to disable it without having to edit my theme.

### Describe the feature

Per-board and global toggles for card counters in lists. Maybe per-list too?

**Comment by janschlatter** [comment]
As for global, can be easily hidden with one line of CSS.

```css
div.kanban-plugin__lane-title-count {
    visibility: hidden;
}
```
