### ISSUE TITLE
[Feature]: Searching Kanban board hides cards which don't match search query

### ISSUE THREAD

**Issue by andrewsardone** [mgmeyers/obsidian-kanban#527]
### Goal or desired outcome of this feature

As an…  
Obsidian Kanban user with lots of cards on a board,
I want…  
to search my board and have cards which don't match my search term completely disappear from the board,
so that…  
cards matching my search are more readily apparent and not initially hidden "below the field".

### Describe the feature

Searching for a card on a Kanban board is a good feature and a common part of workflows. But the current implementation which merely dims the cards unmatched cards is less than ideal.

Cards which match a search query can get lost of the noise of other cards. If a search-query-matched card is "below the folder" of the screen, a user has to scroll the list to find the card. This is made more challenging given that each list scrolls independently. 

### Screenshots, mockups, or videos

**Figure 1: Quick GIF demonstrating the scrolling and manual card foraging after entering a search term**
This would be made better if all the cards disappeared _except_ those that match my search query.
![CleanShot 2022-04-26 at 23 55 32](https://user-images.githubusercontent.com/14554/165437085-1bd871c1-e033-4928-9904-c2946124852c.gif)

**Comment by dominicwhittle** [comment]
At the time of writing (v1.5.1) you can add the following to your custom.css:
This is a very poorly tested stop-gap at best. I would like to see this implemented properly in the plugin, potentially as a board option so we can keep the "grey-out" option on small boards and choose to hide completely on large boards.

```css
.kanban-plugin__lane-items > div {
  margin-top: 0;
}
.kanban-plugin__item,
.kanban-plugin__placeholder {
  margin-top: 4px;
}
.kanban-plugin__item.is-search-miss {
  display: none;
}
```
