### ISSUE TITLE
[Bug]: A scroll bar appears on the right

### ISSUE THREAD

**Issue by deemsd** [mgmeyers/obsidian-kanban#677]
### Describe the bug

![CA6DB586-8829-4C8D-AF06-50C28439045B](https://user-images.githubusercontent.com/117608191/200203523-114b96e4-00a6-482d-a05a-bc657b9b3ae9.png)

The scroll bar appears on the right. If the text is bold, the scroll bar will not appear。

### Steps to reproduce

One of my computers has this problem, and I don't know how to reproduce it

### Operating system

macOS

**Comment by aboudekahil** [comment]
This happened to me too, it's the text within the card overflowing a bit due to 
```css
.kanban-plugin__markdown-preview-view>div>* {
    overflow-x: auto;
}
```

being set
