### ISSUE TITLE
[Bug]: Subbullet checkboxes are partially cut of on the left

### ISSUE THREAD

**Issue by mbbroberg** [mgmeyers/obsidian-kanban#714]
### Describe the bug

Regardless of theme or font choice, sub-bullet checkboxes are cut off when rendered in a kanban card: 

![Screen Shot 2023-01-03 at 10 29 44 AM](https://user-images.githubusercontent.com/1744971/210399632-8b2acc03-a73d-477c-8689-ab1f9f65345b.png)

I extensively use this "subtask" type layout and just noticed this change to the visual. I've tried 3 different themes in light/dark to look for differences but they all are missing the left-most column of pixels that complete the box. 

### Expected Behavior

The box should be visible even as a subbullet.

### Steps to reproduce

Create a card with subbullets following this format: 

Primary task
- [ ] subtask
- [ ] subtask
- [x] subtask

And you'll see what I mean. 

### Operating system

macOS

**Comment by mbbroberg** [comment]
If this is a minor CSS edit I'd be glad to hotfix my setup as soon as someone finds it. Minor UI imperfections unfortunately steal my attention quite easily and I'm eager to fix this. 

Thank you for making my favorite plugin!

**Comment by IljaManakov** [comment]
I can confirm this bug on Ubuntu 20.04.
I appeared recently, presumably with one of the updates. Was fine before.
I do not have any custom CSS in my setup aside from this short snippet for mermaid:
```css
.mermaid svg{
	max-width: 100%;
	height: auto;
}
```

**Comment by Akiriki** [comment]
In case someone wants a workaround by adding some lines of custom css until it's fixed by the creator, heres a snippet:

```css
.kanban-plugin__markdown-preview-view ul,
.kanban-plugin__markdown-preview-view ol {
    padding-inline-start: 34px !important;
}

```


At least it works for me.
Another possible way would be this:

```css
ul>li.task-list-item .task-list-item-checkbox {
    margin-inline-start: calc(var(--checkbox-size) * -1.1) !important;
}
```
