### ISSUE TITLE
Change card or date text color for date(s) that are overdue

### ISSUE THREAD

**Issue by jorgb** [mgmeyers/obsidian-kanban#80]
Hi, 

Now that the KanBan board supports dates, it would be nice if the dates can visually change when they are overdue. For example every day in the past gets a red color, dates in the future grey, and day today green. It is also nice if it can be reflected in the background color of the card but that might require a CSS styling that can be exposed and altered for people with different themes. 

In any case, since my workload can be beautifully visualized in a KanBan view, it reduces the anxiety of forgetting tasks that I should do before a certain date.

**Comment by mgmeyers** [comment]
@jorgb I hope to add settings for this in the future, but it is currently possible via CSS. Cards will have these classes depending on dates and completion status:

- `.kanban-plugin__item.is-future`
- `.kanban-plugin__item.is-today`
- `.kanban-plugin__item.is-past`
- `.kanban-plugin__item.is-complete`


Here's an example:

```css
.kanban-plugin__item.is-future:not(.is-complete)
  .kanban-plugin__item-metadata-date {
  color: var(--text-muted);
}

.kanban-plugin__item.is-today:not(.is-complete)
  .kanban-plugin__item-metadata-date {
  color: var(--interactive-success);
  font-weight: bold;
}

.kanban-plugin__item.is-past:not(.is-complete)
  .kanban-plugin__item-metadata-date {
  color: var(--text-error);
  font-weight: bold;
}

.kanban-plugin__item.is-complete .kanban-plugin__item-markdown {
  text-decoration: line-through;
  text-decoration-color: var(--text-muted);
}
```

**Comment by tlnagy** [comment]
@mgmeyers' example was very helpful but I was using relative dates so I had to add the following definitions to the above ones:

```css
.kanban-plugin__item.is-future:not(.is-complete)
  .kanban-plugin__item-metadata-date-relative {
  color: var(--text-muted);
}

.kanban-plugin__item.is-today:not(.is-complete)
  .kanban-plugin__item-metadata-date-relative {
  color: var(--interactive-success);
  font-weight: bold;
}

.kanban-plugin__item.is-past:not(.is-complete)
  .kanban-plugin__item-metadata-date-relative {
  color: var(--text-error);
  font-weight: bold;
}
```
