### ISSUE TITLE
Add board filtering

### ISSUE THREAD

**Issue by justindirose** [mgmeyers/obsidian-kanban#83]
Since you can easily add Obsidian tags to Kanban cards, it would be neat to be able to filter the board based upon those tags so you can see only the cards with the selected tags. 

Right now, clicking on a tag opens the search pane -- which *can* work if you only use those tags on the board. The caveat here is you can only jump to the markdown view.

This could be implemented via a search box or a tag selector. A search box might be more flexible, though.

**Comment by mgmeyers** [comment]
@justindirose A search box has been implemented! In the future I'll add tag autocomplete to the search box, and possibly other enhancements to make filtering cards easier.

**Comment by justindirose** [comment]
I just updated to 0.3.10, but I'm having difficulty finding the search box. Where should I be seeing it?

**Comment by mgmeyers** [comment]
Yeah, definitely let me know how it feels for you. There are some technical annoyances with completely hiding cards. I would have to disable drag & drop to get that to work, but it is an option

**Comment by skillhacker-code** [comment]
Thank you Mg Meyer the search box is awesome. 

I have a big kanban board and it would be great if you can add an option to toggle between searches and show the card related to search  .

 Like when  we search in a pdf .it show there are 3 searches and when we click the arrow it show each search result .

Thank you

**Comment by alextroop** [comment]
Thank you for your work and for adding searching, using tags and search is what made it replace Trello labels for me.

I am a little confused about the implementation of tags though -- if I use a tag and display it in the card then it is searchable; if I hide it in the card title but show it under the card (as your formal tag display) then it isn't searchable. Or am I missing something about how to use the tags?

**Comment by mgmeyers** [comment]
@alextroop Ah, that's a bug. Tags should definitely be searchable! I'll fix this in the next few days

**Comment by tai-jui** [comment]
Would it be possible for search to also search Metadata fields? Right now the search only searches for the field name, but ignores field values.

**Comment by FeralFlora** [comment]
> Yeah, definitely let me know how it feels for you. There are some technical annoyances with completely hiding cards. I would have to disable drag & drop to get that to work, but it is an option

I think the ability to hide cards would be very valuable.

**Comment by antoinekh** [comment]
I also upvote this. I would really like to be able to filter the board with just a tag to have a clean view

**Comment by ybnd** [comment]
Since the search function adds `.is-search-miss` & `.is-search-hit` classes to the cards, board filtering can be implemented via CSS snippets.
I use the following:

```css
.kanban-plugin__item-wrapper {
  /* originally 4px, moved to child element to ensure hidden cards don't retain their margins */
  margin-top: 0px !important;

  .kanban-plugin__item {
    margin-top: 4px;

    &.is-search-miss {
      /* Hide cards that don't include the search terms */
      display: none;
    }

    &.is-search-hit {
      /* No longer relevant as the hits are the only cards shown */
      box-shadow: none;
    }
  }
}
```
