### ISSUE TITLE
[Feature]: Stack two or more list in a column

### ISSUE THREAD

**Issue by laraib07** [mgmeyers/obsidian-kanban#838]
### Goal or desired outcome of this feature

![Drawing 2023-10-04 12 55 06 excalidraw](https://github.com/mgmeyers/obsidian-kanban/assets/25507825/bf085a24-da1d-4403-aa31-e41f397b5139)

I am trying to stack applied_with_referral and applied_without_referral in same column.

### Describe the feature

Stacking multiple list in same column will unlock greater possibilities and will make kanban more versatile.

### Can you think of any alternatives or work-arounds?

One work-around is to use divider cards with titles.

### Screenshots, mockups, or videos

![Screenshot from 2023-10-04 17-30-41](https://github.com/mgmeyers/obsidian-kanban/assets/25507825/d04a3193-3c57-4af2-82f3-2d739d1a3ae1)

**Comment by dequi** [comment]
Another workaround I've found is to use a CSS-snippet to order the lists in a grid: https://github.com/mgmeyers/obsidian-kanban/issues/237#issuecomment-1817474831

* Create your 7 lists (jobs, asked, applied with, applied without, rejected, got interview, got job)
* Create a [CSS snippet](https://github.com/mgmeyers/obsidian-kanban/issues/237#issuecomment-1646970891) with the following code:

```css
.kanban-plugin__board > div {
    display: grid;
    grid-template-areas: "c1 c2 c3r1 c4r1 c5"
			 "c1 c2 c3r2 c4r2 c5";
    row-gap: 20px;
}

.kanban-plugin__lane-wrapper:nth-of-type(1) { grid-area: c1; }
.kanban-plugin__lane-wrapper:nth-of-type(2) { grid-area: c2; }
.kanban-plugin__lane-wrapper:nth-of-type(3) { grid-area: c3r1; }
.kanban-plugin__lane-wrapper:nth-of-type(4) { grid-area: c3r2; }
.kanban-plugin__lane-wrapper:nth-of-type(5) { grid-area: c4r1; }
.kanban-plugin__lane-wrapper:nth-of-type(6) { grid-area: c4r2; }
.kanban-plugin__lane-wrapper:nth-of-type(7) { grid-area: c5; }

.kanban-plugin__scroll-container.kanban-plugin__horizontal {
    overflow-y: auto;
}
```
* Now your Kanban board looks like this:

![image](https://github.com/mgmeyers/obsidian-kanban/assets/20557540/11869a8c-2eb7-4cf4-8a56-9ca326378605)
