### ISSUE TITLE
[Bug]: kanban title count show ugly style when collapsed horizontal

### ISSUE THREAD

**Issue by l2eused** [mgmeyers/obsidian-kanban#989]
### Describe the bug

when collapsed kanban lane it will rotate 180 deg. but style it doesn't change along with that. 

### Expected Behavior

it can be fix by add style to match collapse lane

in css:
```css
.kanban-plugin__lane-wrapper.collapse-horizontal .kanban-plugin__lane .kanban-plugin__lane-title-count {
    min-height: 20px;
    min-width: unset;
    padding: 6px 0;
}
```

P.S I don't know how to create pull request... so I ended up with create this issue

### Steps to reproduce

1. create kanban list
2. collapse kanban list (kanban lane)

### Operating system

Windows
